[Untested] Fix incorrect behavior when `$_APTMGR` it's a full path to a binary
ilikenwf/apt-fast pull request #189
Opened 2021-03-19 08:50 UTC by guekho64

<h1> Why? </h1>

Just as @DogSledder pointed out in #188, `apt-fast.conf` [states](https://github.com/ilikenwf/apt-fast/blob/5f853c97ddc3704898b47e2e5af9714d68e2ff69/apt-fast.conf#L9) that `$_APTMGR` _may_ contain a full path to a binary rather than a just a name, but in practice, doing so would end up confusing `apt-fast` when trying to detect which package manager was selected, obviously causing an error.

This PR makes use of `basename` command, from [GNU Coreutils](https://www.gnu.org/software/coreutils/basename) to fix #188, which I'm pretty sure it can be found on most GNU/Linux distros, including Debian of course.

2021-03-19 16:39 UTC, Lasall requested changes
Thank you looks quite good. I will test it later.

2021-03-19 16:39 UTC, Lasall commented on apt-fast
> +    read -p 'Press ENTER to exit'
Let's just exit without user interaction.

2021-03-19 16:39 UTC, Lasall commented on apt-fast
> +    exit 64
Where is that code coming from? Here are some standard codes: https://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF

2021-03-20 01:37 UTC, guekho64 commented on apt-fast
> +    read -p 'Press ENTER to exit'
Ok then

2021-03-20 01:37 UTC, guekho64 commented on apt-fast
> +    exit 64
I went through `apt-fast`'s code looking for any kind of convention or pattern related to exit codes, but most exits just use code `1`, which indicates general error, so I though this specific error would be worthy of getting its own code, as it's specially unusual; other candidates could be `126` or `127` as well, but I didn't pick any of those in case I didn't notice if any other line was already using it.

Of course, if above reason doesn't seem to be enough to give this specific error an exit code other than `1`, then there's no problem with that

2021-03-20 09:56 UTC, Lasall commented on apt-fast
> +    exit 64
I suggest let's go with the general error.

2021-03-20 10:06 UTC, Lasall requested changes

2021-03-20 10:06 UTC, Lasall commented on apt-fast
> +# apt-fast v1.9.1
The latest tagged version is 1.9.10, so it should be 1.9.11 here.

2021-03-20 10:17 UTC, Lasall commented on apt-fast
> +
Why won't we use basename... here as well? At least apt would be usable. If we exclude apt from the uri part we can remove APT_SCRIPT_WARNING[] the following line.

2021-03-20 10:21 UTC, Lasall commented on apt-fast
> +fi
I don't quite get the use-case for hard-coding the apt-get path. If that feature is needed then maybe we should get it with command -v or so.

2021-03-20 10:46 UTC, Lasall commented
I've tested the patch a bit and it works as intended.

2021-03-21 05:05 UTC, guekho64 commented on apt-fast
> +# apt-fast v1.9.1
Yep, you're right: Seems it has been a while since that comment was last updated. Maybe README.md also deserves being updated?

2021-03-21 07:28 UTC, guekho64 commented on apt-fast
> +
Given the fact we just use `"${uri_mgr}"` to get package URI's automatically, I'd prefer to directly use `apt-get` above anything else.

<details><summary>Pros</summary>

* According to official Debian documentation, `apt` isn't the [recommended](https://manpages.debian.org/jessie/apt/apt.8.en.html#SCRIPT_USAGE) way to proceed in scripts.
* No matter if we choose `apt-get` or `apt`, we'd be calling the [exact same code](https://salsa.debian.org/apt-team/apt/-/blob/master/apt-private/private-update.cc#L44); the only [differences](https://manpages.debian.org/jessie/apt/apt.8.en.html#DIFFERENCES_TO_APT-GET(8)) between using one or another seem irrelevant for this specific case, unless I'm missing something.

</details>

<details><summary>Cons</summary>

* The only drawback I see here, it's that we'd be blocking users from defining their own way to get package URI's via `"${_APTMGR}"`

</details>

Regarding on whether we should remove `${APT_SCRIPT_WARNING}` or not, I'd rather prefer to leave it there, just to be sure no warnings will be raised ever, even if `apt-get` default options change in the future.

2021-03-21 07:30 UTC, guekho64 commented on apt-fast
> +fi
The purpose of hardcoding `apt-get` path it's precisely to avoid `apt-get` being resolved at a later point, which might be undesired, just as described by @DogSledder in #188. Another option would be to use `"/usr/bin/"$(basename "${_APTMGR}")""`, but either way, we wouldn't be able to avoid hardcoding at all, even if it's just `/usr/bin` or whole `apt-get` path.

AFAIK, `command` built-in just ensures that we'll be calling an external command, even if there's a function with the same name, but that wouldn't help in case we had a setup as described in #188

2021-03-21 12:10 UTC, Lasall commented on apt-fast
> +
Imho the mentioned pros don't outweigh the cons.

2021-03-21 12:16 UTC, Lasall commented on apt-fast
> +fi
Where is it resolved at a later point? To avoid any circular invocations, setting APTMGR to a full path is already fixing the issue (with the basename patch provided in this PR).

2021-03-22 06:02 UTC, guekho64 commented on apt-fast
> +
Alright then, I have no problem with that: I'll rollback that piece of code.

2021-03-22 07:26 UTC, guekho64 commented on apt-fast
> +fi
Of course, that's why `"${real_APT}"` doesn't try to shadow/replace `"${_APTMGR}"` in any way, as doing so isn't its objective: In fact, `"${real_APT}"` was conceived just to deal with what would happen if we try to call `apt-get` as is, which usually has to do with [default values](https://github.com/ilikenwf/apt-fast/blob/5f853c97ddc3704898b47e2e5af9714d68e2ff69/apt-fast#L122) & [fallbacks](https://github.com/ilikenwf/apt-fast/blob/5f853c97ddc3704898b47e2e5af9714d68e2ff69/apt-fast#L328).

<details><summary>This is how I see it</summary>

For example, let's suppose we have a similar setup to the one by @DogSledder, where our shell prioritizes `/usr/local/bin` when looking for binaries in our `$PATH`, so any binaries within `/usr/local/bin` will take precedence over any other binaries, no matter what.

Also, let's suppose we have a symlink like this: `/usr/local/bin/apt-get -> /usr/bin/apt-fast`

Given this scenario, if we call `apt-get` from `apt-fast`, this is what I think will happen:

* Our shell will try to resolve `apt-get`'s location
* `apt-get` will resolve to `/usr/local/bin/apt-get`, completely ignoring `/usr/bin/apt-get`
* `/usr/local/bin/apt-get` it's a symlink pointing to `/usr/bin/apt-fast`
* We'd end up calling ourselves

</details>

2021-03-22 18:50 UTC, Lasall commented on apt-fast
> +# apt-fast v1.9.1
Sure.

2021-03-22 19:05 UTC, Lasall commented on apt-fast
> +fi
Ok but to make it fail one would need to have a redirect from apt-get to apt-fast to get the potential recursive call and also use a non-standard APTMGR. Imho especially the latter case is unlikely to happen. We explicitly support apt-get, apt and aptitude whereas the support for aptitude is not great.
Personally I think creating a link from apt-get to apt-fast is already the first mistake where a shell alias would be sufficient.

I suggest let's get the changes with the basename fix for #188 in and discuss the other changes in a separate PR. I'm willing to get outvoted on that matter if there are more people following your idea.

2021-03-22 19:28 UTC, DogSledder commented on apt-fast
> +fi
I tried a shell alias, but, among other shortcomings, aliases don't seem to be inherited by invoked scripts. I wanted invoked scripts to be redirected to apt-fast.

2021-03-22 23:02 UTC, guekho64 commented on apt-fast
> +fi
> I suggest let's get the changes with the basename fix for #188 in and discuss the other changes in a separate PR. I'm willing to get outvoted on that matter if there are more people following your idea.

Ok, I agree with you: This has become a [Feature Request] on itself, so I'll move anything related to `"${real_APT}"` from this PR to a new one, just keeping the bare essential changes.

2021-03-22 23:30 UTC, guekho64 commented
Thanks for your detailed feedback @Lasall, it's always appreciated :+1:

2021-03-25 18:03 UTC, Lasall approved these changes

2021-03-25 18:08 UTC, merged

2021-03-25 18:08 UTC, Lasall commented
Thanks a lot, your patch is merged.

2023-02-10 21:36 UTC, waturdoingiswrong commented
Reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years with his buddies in the hate group Storm Ryders.

2023-02-13 18:39 UTC, keriadaa reviewed
Dominique Lasserre aka @Lasall is a bully who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up.